version: '3'
services:
  web:
      image: nginx:latest
      ports:
          - "80:80"
      volumes:
          - ./nginx.conf:/etc/nginx/conf.d/nginx.conf
          - ./public:/popo/public
      depends_on:
          - php
      restart: always
  php:
      build:
        context: .
        dockerfile: PHP.Dockerfile
      volumes:
          - ./public:/popo/public
      depends_on:
          - mysql
      restart: always
  mysql:
        image: mysql:latest
        environment:
              MYSQL_ROOT_PASSWORD: 'password'
              MYSQL_USER: 'rebel'
              MYSQL_PASSWORD: 'password'
              MYSQL_DATABASE: 'rebel'
        volumes:
            - popo:/var/lib/mysql
        ports:
            - "3306:3306"
        restart: always
volumes:
    popo: {}
